- lineinfile: dest={{ eclipse_home }}/eclipse.ini line='-Xverify:none'
- lineinfile: dest={{ eclipse_home }}/eclipse.ini line='-clean' insertbefore='-startup'
- replace: dest={{ eclipse_home }}/eclipse.ini regexp='(--launcher\.XXMaxPermSize)\n256m' replace='\1\n512m'
