- name: Downloading STS
  get_url: url={{ sts_url }} dest={{ sts_download_dir }}/{{ sts_file_dist }}
- name: Installing STS
  unarchive: src={{ sts_download_dir }}/{{ sts_file_dist }} dest={{ sts_install_dir }}
- name: Creating desktop icon
  template: src=STS.j2 dest=/usr/share/applications/STS.desktop
- set_fact: sts_home=/opt/sts-bundle/sts-{{ sts_version }}
- set_fact: sts="{{ sts_home }}/STS"
