galaxy_info:
  author: Carlos Alexandro Becker
  description: Customized Eclipse for Java SE/EE development
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: MacOSX
      versions:
        - all
  galaxy_tags:
    - development
    - ide
    - java
    - eclipse
dependencies: []
